menu:
  - page: Blog
    directory: ./
  - page: Archive
    directory: archives/
  - page: About
    directory: about/
bio:
  intro: 程序酱 运动爱好者
  nickname: creekwax
  social:
    Mail: creekwax@gmail.com 
    Github: https://github.com/creekwax
